export const CREATE_RATING_REQUEST = 'CREATE_RATING_REQUEST';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';

export const GET_PRODUCTS_RATING_REQUEST = 'GET_PRODUCTS_RATING_REQUEST';
export const GET_PRODUCTS_RATING_SUCCESS = 'GET_PRODUCTS_RATING_SUCCESS';
export const GET_PRODUCTS_RATING_FAILURE = 'GET_PRODUCTS_RATING_FAILURE';