export const CREATE_SUBCATEGORY_REQUEST = "CREATE_SUBCATEGORY_REQUEST";
export const CREATE_SUBCATEGORY_SUCCESS = "CREATE_SUBCATEGORY_SUCCESS";
export const CREATE_SUBCATEGORY_FAILURE = "CREATE_SUBCATEGORY_FAILURE";

export const GET_ALL_SUBCATEGORIES_REQUEST = "GET_ALL_SUBCATEGORIES_REQUEST";
export const GET_ALL_SUBCATEGORIES_SUCCESS = "GET_ALL_SUBCATEGORIES_SUCCESS";
export const GET_ALL_SUBCATEGORIES_FAILURE = "GET_ALL_SUBCATEGORIES_FAILURE";

export const GET_SUBCATEGORY_BY_ID_REQUEST = "GET_SUBCATEGORY_BY_ID_REQUEST";
export const GET_SUBCATEGORY_BY_ID_SUCCESS = "GET_SUBCATEGORY_BY_ID_SUCCESS";
export const GET_SUBCATEGORY_BY_ID_FAILURE = "GET_SUBCATEGORY_BY_ID_FAILURE";

export const UPDATE_SUBCATEGORY_REQUEST = "UPDATE_SUBCATEGORY_REQUEST";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_FAILURE = "UPDATE_SUBCATEGORY_FAILURE";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAILURE = "DELETE_SUBCATEGORY_FAILURE";

export const GET_SUBCATEGORIES_BY_CATEGORY_ID_REQUEST = "GET_SUBCATEGORIES_BY_CATEGORY_ID_REQUEST";
export const GET_SUBCATEGORIES_BY_CATEGORY_ID_SUCCESS = "GET_SUBCATEGORIES_BY_CATEGORY_ID_SUCCESS";
export const GET_SUBCATEGORIES_BY_CATEGORY_ID_FAILURE = "GET_SUBCATEGORIES_BY_CATEGORY_ID_FAILURE";
